kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: hipster-shop
  name: kubeinvaders-rolebinding
subjects:
- kind: ServiceAccount
  name: kubeinvaders 
  namespace: kubeinvaders
roleRef:
  kind: Role
  name: kubeinvaders-role
  apiGroup: rbac.authorization.k8s.io
